### ISSUE TITLE
Setup failed for unifiprotect: Unable to import component

### ISSUE THREAD

**Issue by bigbangus** [linuxserver/docker-homeassistant#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Unifi Protect add in should work.

## Current Behavior
Unifi Protect add in doesn't start with following error:
Setup failed for unifiprotect: Unable to import component: cannot import name 'get_terminal_size' from 'click.termui' (/usr/lib/python3.9/site-packages/click/termui.py)

## Steps to Reproduce
Happens when upgrading from 2022.4 to 2022.5.1

## Environment
**OS:** Unraid 6.10rc4
**CPU architecture:** x86_64
**How docker service was installed:** Unraid app store, ghcr.io/linuxserver/homeassistant:2022.5.1-ls72

## Docker logs
Setup failed for unifiprotect: Unable to import component: cannot import name 'get_terminal_size' from 'click.termui' (/usr/lib/python3.9/site-packages/click/termui.py)
8:22:31 AM – (ERROR) setup.py

**Comment by bigbangus** [comment]
Is additional information required to solve this issue?

**Comment by bigbangus** [comment]
Fixed in 2022.5.4-ls75 from what I can tell. Something to do with python software or package versions?
